PnVanoise/cables

- web/cables.html
> updating cables.html

- web/js/services/mapServices.js
adding var fixed #25 
please review @pgiraud
> Xaadim display geom data

- web/js/templates/eqPoteauxErdf/detail.htm
- web/js/templates/eqPoteauxErdf/edit.htm
Removed map from equipements poteaux edit.htm and detail.htm
> remove map block and reindentation in detail.html and edit.html

- web/js/services/mapServices.js
> Xaadim fixing click on geom

- web/css/app.css
- web/js/templates/display/legendLayer.htm
- web/js/templates/display/map.htm
> Use real checkboxes in legend

- web/js/controleurs/mortalitesCtrl.js
- web/js/directives/formDirectives.js
- web/js/services/mapServices.js
With this pull request editing control are added and removed from map when required.
> manage editing controls

- web/js/controleurs/eqPoteauxErdfCtrl.js
- web/js/controleurs/eqTronconsErdfCtrl.js
- web/js/controleurs/nidificationsCtrl.js
- web/js/controleurs/observationsCtrl.js
- web/js/controleurs/poteauxErdfCtrl.js
- web/js/controleurs/tronconsErdfCtrl.js
- web/js/controleurs/zonesSensiblesCtrl.js
Fixed #67 
Cant I merge @ClaireLagaye ?
> adding title label on details view

- web/js/controleurs/cablesGlobalCtrl.js
- web/js/controleurs/eqPoteauxErdfCtrl.js
- web/js/controleurs/eqTronconsErdfCtrl.js
- web/js/controleurs/nidificationsCtrl.js
- web/js/controleurs/observationsCtrl.js
- web/js/controleurs/poteauxErdfCtrl.js
- web/js/controleurs/tronconsErdfCtrl.js
- web/js/controleurs/zonesSensiblesCtrl.js
Fixed #71 Can I merge @ClaireLagaye ?
> adding create button in tab

- web/js/controleurs/cablesGlobalCtrl.js
- web/js/services/mapServices.js
> adding spinner for data loading

- web/cables.html
- web/css/login/login.css
- web/js/app.js
- web/js/controleurs/cablesGlobalCtrl.js
- web/js/templates/cables/category.htm
- web/js/templates/login.htm
Can I merge @ClaireLagaye ? 
Fixed #79
> login page fixed, map hide when user not connected

- web/js/services/mapServices.js
Ajout d'une condition undefined sur _id dans méthode zoomToItem dans mapservice
> Suppression erreur get bounds of undefined sur affichage page create

- web/css/app.css
- web/js/templates/display/field.htm
> css details elements

- web/js/templates/photosPoteauxErdf/edit.htm
- web/js/templates/photosTronconErdf/edit.htm
> fixing photos edit page

- web/css/app.css
- web/css/login/login.css
- web/js/controleurs/photosPoteauxErdfCtrl.js
- web/js/controleurs/photosTronconsErdfCtrl.js
- web/js/templates/photosPoteauxErdf/detail.htm
- web/js/templates/photosTronconErdf/detail.htm
> fixing photo details view and some css

- web/js/directives/formDirectives.js
> replacing mapService.getMap() for map in geometry directive

- src/PNV/CablesBundle/Resources/clientConf/TInventairePoteauxErdf/form.yml
- src/PNV/CablesBundle/Resources/clientConf/TInventaireTronconsErdf/form.yml
fixes issue #99 
@xaadim please comment
> Make risk fields mandatory when creating or editing poteaux and troncons

- web/js/templates/display/map.htm
> collapsed in poteau erdf in legend block

- web/js/controleurs/poteauxErdfCtrl.js
> fixing label in detail and edit poteaux

- web/js/services/mapServices.js
> Removed old initializecarte, changed function name from init to initmap

- web/js/controleurs/cablesGlobalCtrl.js
- web/js/services/mapServices.js
- web/js/templates/cables/category.htm
Nettoyage et ajout de commentaires dans mapservices.js, cablesGlobalCtrl.js et category.js
> nettoyage et ajout de commentaire

- src/PNV/CablesBundle/Resources/clientConf/TEquipementsPoteauxErdf/detail.yml
- src/PNV/CablesBundle/Resources/clientConf/TEquipementsTronconsErdf/detail.yml
- src/PNV/CablesBundle/Resources/clientConf/TInventairePoteauxErdf/detail.yml
- src/PNV/CablesBundle/Resources/clientConf/TInventaireTronconsErdf/detail.yml
- src/PNV/CablesBundle/Resources/clientConf/TPhotosPoteauxErdf/detail.yml
- src/PNV/CablesBundle/Resources/clientConf/TPhotosTronconsErdf/detail.yml
- web/js/directives/displayDirectives.js
- web/js/templates/display/baseDetail.htm
- web/js/templates/display/field.htm
> Clagaye clickable elements

- web/css/app.css
- web/js/services/colorServices.js
> Change selected color to pink for all layers, fixes #103

- src/PNV/CablesBundle/Services/TCasMortaliteService.php
- web/cables.html
- web/js/app.js
- web/js/controleurs/mortalitesCtrl.js
- web/js/directives/formDirectives.js
- web/js/templates/form/datepick.htm
@Chrispnv il fallait lui dire d'envoyer la date choisie par l'utilisateur.
> Fix date dans saisie
